name: odra-casper-ci

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
    paths-ignore:
      - "**.md"

jobs:
  check_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: apt update
      - run: make prepare
      - run: make build-test-env
      - run: make check-lint
      - run: make test
  integration_tests:
    runs-on: ubuntu-latest
    needs: check_and_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Clone odra-examples
        uses: actions/checkout@v2
        with:
          repository: odradev/odra-examples
          path: odra-examples
      - name: Clone odra
        uses: actions/checkout@v2
        with:
          repository: odradev/odra
          path: odra
      - name: Prepare casper-backend to run examples
        working-directory: backend
        run: sed -i '/odra = { version/c\odra = { path = "../odra/core", default-features = false, features = [ "wasm" ] }' Cargo.toml
      - name: Prepare casper-shared to run examples
        working-directory: shared
        run: sed -i '/odra-types/c\odra-types = { path = "../odra/types" }' Cargo.toml
      - name: Prepare casper-test-env to run examples
        working-directory: test_env
        run: sed -i '/odra = { version/c\odra = { path = "../odra/core", default-features = false, features = [ "wasm-test" ] }' Cargo.toml
      - name: Prepare examples to use local odra
        working-directory: odra-examples
        run: sed -i '/default-features/c\odra = { path = "../odra/core", default-features = false }' Cargo.toml &&
          sed -i '/version/c\path = "../"' Odra.toml
      - name: Run tests
        working-directory: odra-examples
        run: sudo apt update &&
          rustup component add rustfmt &&
          make prepare &&
          make test