name: odra-casper-publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN} -p odra-casper-shared && sleep 60
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN} -p odra-casper-backend && sleep 60
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN} -p odra-casper-test-env
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}